config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/events/pending', to: 'events#my_events', as: 'my_events'
  get '/events/:id/delete', to: 'events#delete', as: 'delete_event'

  resources :events, except: [:edit] do
    resources :requests, only: [:new, :create]
    resources :users, only: [] do
      resources :messages, only: [:create]
    end
  end
  get '/requests/submitted/:id', to: 'requests#submitted', as: 'submitted_request'
  get '/events/:event_id/requests/incoming', to: 'requests#incoming', as: 'incoming_requests'
  resources :requests, only: [:show, :update]

  get '/inbox', to: 'messages#index', as: 'messages'
  get '/inbox/:user_id', to: 'messages#new', as: 'new_message'

  get '/welcome', to: 'pages#welcome', as: 'welcome'
  get '/calendar', to: 'pages#calendar', as: 'calendar'
  patch '/', to: 'pages#update_location'

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice && notice.length > 0 %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert && alert.length > 0  %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
    <header>
      <span class="menu-control-open" id="menuControlOpen">
        <i class="fas fa-bars"></i>
      </span>
      <div class="menu">
        <div class="menu-inner">
          <span class="menu-control-close" id="menuControlClose">
            <i class="fas fa-bars"></i>
          </span>
          <nav>
            <%= link_to welcome_path do %>
              <% if current_user.photo.attached? %>
                <%= cl_image_tag url_for(current_user.photo), class: "border navbar-avatar mr-3" %>
              <% else %>
                <%= image_tag "https://res.cloudinary.com/dkbbawtjw/image/upload/v1589987704/art-bnb/default_icon_c0dy7j.png", class: "border navbar-avatar mr-3" %>
              <% end %>
            <% end %>
            <%= link_to "Home", root_path %>
            <%= link_to "Inbox", messages_path %>
            <%= link_to "Suggest an event", new_event_path %>
            <%= link_to "My Calendar", calendar_path %>
            <%= link_to "Choose a Buddy", my_events_path %>
            <%= link_to "Edit Profile", edit_user_registration_path %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </nav>
        </div>
      </div>
    </header>
    <div id="dim-background"></div>
<% end %>

app/views/shared/_navbarbottom.html.erb
<% if user_signed_in? %>
  <div class="navbar-bottom">
    <%= link_to root_path do %><span class="navbar-bottom-item"><i class="fa fa-search"></i></span><% end %>
    <%= link_to new_event_path do %><span class="navbar-bottom-item"><i class="fas fa-plus"></i></span><% end %>
    <%= link_to calendar_path do %><span class="navbar-bottom-item"><i class="far fa-calendar-alt"></i></span><% end %>
    <%= link_to messages_path do %><span class="navbar-bottom-item"><i class="far fa-comments"></i></span><% end %>
  </div>
<% end %>