config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/events/pending', to: 'events#my_events', as: 'my_events'
  get '/events/:id/delete', to: 'events#delete', as: 'delete_event'

  resources :events, except: [:edit] do
    resources :requests, only: [:new, :create]
    resources :users, only: [] do
      resources :messages, only: [:create]
    end
  end
  get '/requests/submitted/:id', to: 'requests#submitted', as: 'submitted_request'
  get '/events/:event_id/requests/incoming', to: 'requests#incoming', as: 'incoming_requests'
  resources :requests, only: [:show, :update]

  get '/inbox', to: 'messages#index', as: 'messages'
  get '/inbox/:user_id', to: 'messages#new', as: 'new_message'

  get '/welcome', to: 'pages#welcome', as: 'welcome'
  get '/calendar', to: 'pages#calendar', as: 'calendar'
  patch '/', to: 'pages#update_location'

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :requests, dependent: :destroy
  has_many :event_categories, dependent: :destroy
  has_many :categories, through: :event_categories
  has_one_attached :photo
  validates :user, :name, :date_time, :address, :photo, :description, presence: true
  validates :description, length: { maximum: 150 }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # Calendar stuff:

    def start_time
        self.date_time
    end
    def end_time
        self.date_time
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    # => GET    /events
    @user = current_user
    if @user == nil || @user.search_location == "" || @user.search_location == nil
      redirect_to welcome_path
    end
    @events = Event.all
    if params[:date].present?
      @date = params[:date]
      @events = @events.where('date_time BETWEEN ? AND ?', DateTime.parse(params[:date]).beginning_of_day, DateTime.parse(params[:date]).end_of_day).where("address ILIKE ?", "%#{@user.search_location}%").includes(:categories, :user).with_attached_photo
    end
  end

  def show
    # => GET    /events/:id
    @event = Event.find(params[:id])
  end

  def new
    # => GET    /events/new
    @event = Event.new
  end

  def create
    # => POST   /events
    @event = Event.new(event_params)
    @event.user = current_user
    if params[:event][:category_ids].length != 0 && params[:event][:category_ids].length < 4 && @event.save
      category_ids = params[:event][:category_ids]
      category_ids.each do |catetogy_id|
        EventCategory.create(category_id: catetogy_id, event_id: @event.id)
      end
      redirect_to event_path(@event)
    else
      @event.valid?
      p params[:event][:category_ids]
      flash[:notice] = "Please select up to 3 categories" if params[:event][:category_ids].length > 3 || params[:event][:category_ids].length == 0
      render :new
    end
  end

  def delete
    # => GET    /events/:id/delete
    @event = Event.find(params[:id])
    @event.destroy!
  end

  def destroy
    # => DELETE /events/:id
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def my_events
    # => GET    /events/pending, prefix: my_events
    @events = current_user.events
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:photo, :name, :user, :category, :address, :date_time, :description)
  end

end

app/views/events/_event_card.html.erb
        <div class="card-product">
          <%#= link_to event_path(event), style: "width: 45%;" do %>
          <%= link_to '', event_path(event), style:"width: 45%; background-size: cover; background-position: center; background-image: url('#{cl_image_path url_for(event.photo), height: 300, width: 400, crop: :fill}')"%>
          <%# end %>

          <div class="flex-column card-right">
            <ul class="card-product-infos ml-2">
              <%= link_to event_path(event) do %>
                <li><h2 style="margin: 0"><%= event.name %></h2></li>
              <% end %>
                <li style="font-size: 12px; margin: 0; margin-bottom:8px"><i class="fas fa-calendar"></i> <%= event.date_time.strftime("%m/%d/%Y") %> - <%= event.date_time.strftime("%I:%M%p") %></li>
                <li class="event-card-address" style="font-size: 12px;"><i class="fas fa-map-marker-alt"></i> <%= event.address %></li>
            </ul>

            <div class="d-flex pb-1">
              <% unless event.categories.first.nil? %>
                <span class="card-filter ml-3" style="background-color: <%= event.categories.first.color %>"><%= event.categories.first.name %></span>
              <% end %>
              <% unless event.categories.second.nil? %>
                <span class="card-filter" style="background-color: <%= event.categories.second.color %>"><%= event.categories.second.name %></span>
              <% end %>
            </div>
                <div>
                  <%= cl_image_tag(event.user.photo.key, class: "card-avatar") %>
                </div>
          </div>
        </div>

app/views/events/index.html.erb
<%= link_to root_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div class="container">

  <div class="w-100">
    <% if @date.present? %>
    <div style="width: 90vw d-flex">
      <h1 class="title py-3" style="width: 300px; font-size: 26px; margin-right: 30px" id="filters">Events for <%= @date %></h1>
    </div>
    <% else %>
      <h1 class="title">All events</h1>
    <% end %>
  </div>

  <div class="d-flex">

    <div class="navbar-dropdown-categories">
      <%= form_tag("/") do %>
        <%= select_tag("categories", options_for_select(["outdoors", "just drinks", "live music", "karaoke", "theater", "other"], "outdoors") ) %>
        <%= submit_tag(">") %>
      <% end %>
    </div>

    <div class="navbar-dropdown-time">
      <%= form_tag("/") do %>
        <%= select_tag("time", options_for_select(["11:00am", "12:00pm", "1:00pm", "2:00pm", "3:00pm", "4:00pm", "5:00pm", "6:00pm", "7:00pm", "8:00pm", "9:00pm", "10:00pm"], "11:00am") ) %>
        <%= submit_tag(">") %>
      <% end %>
    </div>
  </div>

  <% if @events.length == 0 %>
    <p class="mt-4">No events for this date... :(</p>
  <% else %>
        <div class="d-flex flex-column-reverse mt-4" style="width: 360px">
          <% @events.each do |event|  %>
            <%= render partial: "event_card", locals: { event: event } %>
          <% end %>
        </div>
  <% end %>
</div>

app/views/events/my_events.html.erb
<%= link_to root_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div class="container">

<div style="width: 90vw d-flex">
<h1 class="title py-3" style="width: 260px; font-size: 26px; margin-right: 60px" id="filters">Choose a buddy for your activities!</h1>
</div>
  <% if @events.length == 0 %>
    <p>You don't have any events!</p>
    <%= link_to "Suggest an event", new_event_path, class: "btn btn-primary" %>
  <% end %>


    <div class="d-flex flex-column-reverse" style="width: 360px">
      <% @events.each do |event|  %>
        <div class="card-product">
          <%= link_to '', incoming_requests_path(event), style:"width: 45%; background-size: cover; background-position: center; background-image: url('#{cl_image_path url_for(event.photo), height: 300, width: 400, crop: :fill}')"%>

          <div class="flex-column card-right">
            <ul class="card-product-infos ml-2">
              <%= link_to incoming_requests_path(event) do %>
                <li><h2 style="margin: 0;max-width: 156px !important; white-space:nowrap; max-height: 20px;"><%= event.name %></h2></li>
              <% end %>
              <li style="font-size: 12px; margin: 0"><i class="fas fa-calendar"></i> <%= event.date_time.strftime("%m/%d/%Y") %> - <%= event.date_time.strftime("%I:%M%p") %></li>
              <li style="font-size: 12px;"><i class="fas fa-map-marker-alt"></i> <%= event.address %></li>
            </ul>

            <%= link_to 'Choose Buddy', incoming_requests_path(event), class: "btn btn-primary mb-3 ml-3" %>

          </div>
        </div>
      <% end %>
    </div>

</div>

app/views/events/new.html.erb
<%= link_to root_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div class="container">
  <div>
    <div class="form">

    <div style="width: 90vw d-flex">
      <h1 class="title py-3" style="width: 250px; font-size: 26px; margin-left: 30px" id="filters"><strong>Suggest an event</strong></h1>
    </div>
      <%= simple_form_for @event, html: {class: "py-2 display-time"}  do |f| %>
        <%= f.input :name, placeholder: 'Event name', label: false, input_html: { class: 'my-3' }%>
        <%= f.input :photo, placeholder: 'photo', label: false, input_html: { class: 'my-2 mb-3 pt-2 pl-1' } %>

<div class="form-group datetime required event_date_time">
<div class="d-flex flex-column justify-content-between align-items-center">
<div class="mb-2 d-flex flex-row justify-content-between align-items-center my-2">
<select id="event_date_time_1i" name="event[date_time(1i)]" class="form-control mx-1 datetime required">
<option value="2015">2015</option>
<option value="2016">2016</option>
<option value="2017">2017</option>
<option value="2018">2018</option>
<option value="2019">2019</option>
<option value="2020" selected="selected">2020</option>
<option value="2021">2021</option>
<option value="2022">2022</option>
<option value="2023">2023</option>
<option value="2024">2024</option>
<option value="2025">2025</option>
</select>
<select id="event_date_time_2i" name="event[date_time(2i)]" class="form-control mx-1 datetime required" style="width: 190px;">
<option value="1">January</option>
<option value="2">February</option>
<option value="3">March</option>
<option value="4">April</option>
<option value="5">May</option>
<option value="6" selected="selected">June</option>
<option value="7">July</option>
<option value="8">August</option>
<option value="9">September</option>
<option value="10">October</option>
<option value="11">November</option>
<option value="12">December</option>
</select>
<select id="event_date_time_3i" name="event[date_time(3i)]" class="form-control mx-1 datetime required">
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4" selected="selected">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select></div></div>
<div class="d-flex flex-row justify-content-start align-items-center">
<select id="event_date_time_4i" name="event[date_time(4i)]" class="form-control mx-1 datetime required" style="width: 103px;">
<option value="00">00</option>
<option value="01">01</option>
<option value="02">02</option>
<option value="03">03</option>
<option value="04">04</option>
<option value="05">05</option>
<option value="06">06</option>
<option value="07">07</option>
<option value="08">08</option>
<option value="09">09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18" selected="selected">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
</select>
 : <select id="event_date_time_5i" name="event[date_time(5i)]" class="form-control mx-1 datetime required" style="width: 100px;">
<option value="00">00</option>
<option value="01">01</option>
<option value="02">02</option>
<option value="03">03</option>
<option value="04">04</option>
<option value="05">05</option>
<option value="06">06</option>
<option value="07">07</option>
<option value="08">08</option>
<option value="09">09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
<option value="32">32</option>
<option value="33">33</option>
<option value="34">34</option>
<option value="35">35</option>
<option value="36">36</option>
<option value="37">37</option>
<option value="38">38</option>
<option value="39">39</option>
<option value="40">40</option>
<option value="41">41</option>
<option value="42">42</option>
<option value="43">43</option>
<option value="44">44</option>
<option value="45">45</option>
<option value="46">46</option>
<option value="47">47</option>
<option value="48">48</option>
<option value="49">49</option>
<option value="50">50</option>
<option value="51">51</option>
<option value="52">52</option>
<option value="53">53</option>
<option value="54">54</option>
<option value="55">55</option>
<option value="56">56</option>
<option value="57">57</option>
<option value="58" selected="selected">58</option>
<option value="59">59</option>
</select>
</div>
</div>

        <%= f.input :address, placeholder: 'Address', label: false, input_html: { class: 'my-2' } %>

        <p class="pl-2">Pick your category (max 3):</p>

        <div class="d-flex">

        <input class="d-none" type="checkbox" value="1" name="event[category_ids][]" id="event_category_ids_1">
        <label class="filter deselected-filter" style="background-color: <%= Category.find_by(id: 1).color %>" for="event_category_ids_1">outdoors</label>

        <input class="d-none" type="checkbox" value="2" name="event[category_ids][]" id="event_category_ids_2">
        <label class="filter deselected-filter" style="background-color: <%= Category.find_by(id: 2).color %>" for="event_category_ids_2">live music</label>

        <input class="d-none" type="checkbox" value="3" name="event[category_ids][]" id="event_category_ids_3">
        <label class="filter deselected-filter" style="background-color: <%= Category.find_by(id: 3).color %>" for="event_category_ids_3">food</label>

        <input class="d-none" type="checkbox" value="4" name="event[category_ids][]" id="event_category_ids_4">
        <label class="filter deselected-filter" style="background-color: <%= Category.find_by(id: 4).color %>" for="event_category_ids_4">drinks</label>

        </div>
        <div class="d-flex">

        <input class="d-none" type="checkbox" value="5" name="event[category_ids][]" id="event_category_ids_5">
        <label class="filter deselected-filter" style="background-color: <%= Category.find_by(id: 5).color %>" for="event_category_ids_5">sports</label>

        <input class="d-none" type="checkbox" value="6" name="event[category_ids][]" id="event_category_ids_6">
        <label class="filter deselected-filter" style="background-color: <%= Category.find_by(id: 6).color %>" for="event_category_ids_6">theater</label>

        <input class="d-none" type="checkbox" value="7" name="event[category_ids][]" id="event_category_ids_7">
        <label class="filter deselected-filter" style="background-color: <%= Category.find_by(id: 7).color %>" for="event_category_ids_7">festival</label>

        <input class="d-none" type="checkbox" value="8" name="event[category_ids][]" id="event_category_ids_8">
        <label class="filter deselected-filter" style="background-color: <%= Category.find_by(id: 8).color %>" for="event_category_ids_8">other</label>

        </div>

        <div class="description mt-4 mb-0 pb-0">
            <%= f.input :ticket_url, placeholder: 'Ticket URL (optional)', required: false, label: false, input_html: { class: 'py-2' }  %>
            <%= f.input :description, placeholder: 'Add a description to your event', label: false, input_html: { class: 'py-2' }  %>
            <div style="display: flex; justify-content: center">
              <%= f.submit 'Save', class: "btn btn-primary px-4 my-3 mr-1" %>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%= link_to root_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div id="events-show" class="container", style="height: 98vh">
  <div class="card shadow bg-white rounded width: 50rem;">
    <div class="card-show" style="margin-bottom:0; ">

      <div style="max-width: 730px; max-height: 225px; background-image: url('<%= cl_image_path @event.photo.key, crop: :fill %>')" class="event-banner">

        <div style="text-align:right;" class="event-avatar">
          <div data-toggle="modal" data-target="#exampleModalCenter">
            <%= cl_image_tag @event.user.photo.key, crop: :fill, class: "avatar-medium mr-4" %>
          </div>
        </div>
        <% if @event.user == current_user %>
          <div style="text-align:right; width:100%; padding:0;" class="event-delete">
            <div id="trash" class="btn btn-light" data-toggle="modal" data-target="#event-<%= @event.id %>">
              <i class="fas fa-trash"></i>
            </div>
          </div>
        <% end %>
      </div>

      <div class="event-body" style="padding: 12px 20px 20px 20px; min-height: 370px">

        <div class="cards description" style="margin-bottom: 0">
          <h2 style="margin: 0"><strong><%= @event.name %></h2></strong><br>
          <p style="color:gray; font-size: 16px, margin: 0"><i class="fas fa-calendar"></i> <%= @event.date_time.strftime("%m/%d/%Y") %> - <%= @event.date_time.strftime("%I:%M%p") %></p>
          <p style="color:gray"><i class="fas fa-map-marker-alt"></i> <%= @event.address %></p>
          <p><%= @event.ticket_url %></p>
          <p><%= @event.description %></p>
          <% if @event.user == current_user %>
            <p><%= link_to "Check incoming requests", incoming_requests_path(@event), class:"btn btn-primary" %> </p>
          <% else %>
            <%= link_to "Apply", new_event_request_path(@event), class:"btn btn-primary" %>
          <% end %>
        </div>

      </div>


      <%# # Delete request Modal stuff, do not change %>
      <div class="modal fade" style="overflow-y: hidden;" id="event-<%= @event.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel"></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to delete this event?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= link_to 'Delete', event_path(@event), method: :delete, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
      <%# # Delete request Modal stuff, do not change %>

      <!-- Profile Modal, do not change! -->
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content" style="margin-bottom:120px;height:500px;border-radius: 6px">
            <div>
              <h5 class="modal-title" id="exampleModalLongTitle"> </h5>
              <button type="button" class="close pt-3 pr-3" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" style="margin:20px" >

              <div style="text-align:center;">
                <%= cl_image_tag @event.user.photo.key, crop: :fill, class: "avatar-large" %>
              </div><br>
              <h4 style="text-align:center;"> <%= @event.user.first_name %> <%= @event.user.last_name %> </h4>
              <hr style="margin-top:5px;background-color:#FF7662;height:2px;width:45%;text-align:left;margin-left:" >
              Languages: <%= @event.user.languages.map(&:name).join(', ') %><br>
              Age: <%= @event.user.age %><br><br>
              <%= @event.user.bio %>
            </div>
          </div>
        </div>
      </div>
      <!-- Profile Modal, do not change! -->

    </div>
  </div>
</div>