config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/events/pending', to: 'events#my_events', as: 'my_events'
  get '/events/:id/delete', to: 'events#delete', as: 'delete_event'

  resources :events, except: [:edit] do
    resources :requests, only: [:new, :create]
    resources :users, only: [] do
      resources :messages, only: [:create]
    end
  end
  get '/requests/submitted/:id', to: 'requests#submitted', as: 'submitted_request'
  get '/events/:event_id/requests/incoming', to: 'requests#incoming', as: 'incoming_requests'
  resources :requests, only: [:show, :update]

  get '/inbox', to: 'messages#index', as: 'messages'
  get '/inbox/:user_id', to: 'messages#new', as: 'new_message'

  get '/welcome', to: 'pages#welcome', as: 'welcome'
  get '/calendar', to: 'pages#calendar', as: 'calendar'
  patch '/', to: 'pages#update_location'

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user, :event, :motivation, :status, presence: true

  def pending? 
    status == "Pending"
  end

  def accepted?
    status == "Accepted"
  end

  def declined?
    status == "Declined"
  end

  def cancelled?
    status == "Cancelled"
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def new
    # => GET    /requests/new
    @event = Event.find(params[:event_id])
    @request = Request.new
  end

  def create
    # => POST   /requests
    @event = Event.find(params[:event_id])
    @new_request = Request.new(request_params)
    @new_request.status = "Pending"
    @new_request.event = @event

    @new_request.user = current_user
    if @new_request.save
      # to change later
      redirect_to submitted_request_path(@new_request)
    else
      render :new
    end
  end

  def update
    # => PATCH  /requests/:id
    session[:return_to] = request.referer
    redirect_to_path = session.delete(:return_to)
    @request = Request.find(params[:id])
    if ["Accepted", "Declined", "Deleted"].include?(status_params[:status])
      @request.status = status_params[:status]
      @request.save!
      if status_params[:status] == "Accepted"
        Message.create(sender: current_user, receiver: @request.user, content: "(Automated Message) -    I picked you! Let's start planning :)")
        @request.event.requests.where(status: "Pending").update_all(status: "Declined")
        redirect_to_path =  new_message_path(@request.user, {event: @request.event.id} )
      end
    end

    redirect_to redirect_to_path
  end

  def submitted
    # => GET    /requests/submitted/:id
    @request = Request.where(user: current_user).last
  end

  def incoming
    # => GET    /events/:event_id/requests/incoming
    @event = Event.find(params[:event_id])
    # @requests = @event.requests
  end

  def show
    # => GET    /requests/:id
    @request = Request.find(params[:id])
  end

  private

  def request_params
    params.require(:request).permit(:motivation)
  end

  def status_params
    params.require(:request).permit(:status)
  end

end

app/views/requests/incoming.html.erb
<%= link_to my_events_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div class="container">
    <div class="row">
<% if @event.requests.present? %>

      <h1 class="title"> <%= @event.name %> </h1>
      <ul>
        <li style="font-size: 14px; margin-bottom: 6px;"><i class="fas fa-calendar" id="incoming-requests"></i> <%= @event.date_time.strftime("%m/%d/%Y") %> - <%= @event.date_time.strftime("%I:%M%p") %></li>
        <li class="event-card-address" style="font-size: 14px;"><i class="fas fa-map-marker-alt" id="incoming-requests"></i> <%= @event.address %></li>
      </ul>
      <% @event.requests.each do |request| %>
        <div class="card card-request shadow p-3 mb-5 bg-white rounded" style="width: 30rem;" style="height: calc(100vh - 160px); position: relative;">

          <div class="row no-gutters">
          <div class="d-flex col-md-4">
            <button type="button" class="btn btn-ghost" data-toggle="modal" data-target="#exampleModalCenter-<%= request.id %>">
              <%= cl_image_tag url_for(request.user.photo), class:"avatar-request" %>
            </button>
            <div class="request-info">
              <p style="font-weight:bold;"> <%= request.user.first_name %>, <%= request.user.age %>  </p>
              <p> <cite><%= request.motivation %><cite> </p>
            </div>
          </div>
          <div class="col-md-8">
            <% if request.pending? %>
              <div class="d-flex justify-content-end align-items-center">
                <%= form_for request, url: request_path(request), method: :patch do |f| %>
                  <%= f.hidden_field :status, value: "Accepted" %>
                  <%= f.submit 'Choose me!', class: "btn btn-success choose-me" %>
                <% end %>
              </div>
            <% elsif request.accepted? %>
              <span class="green-text font-weight-bold mt-3" style="color:MediumSeaGreen;"><%= request.status %></span>
            <% elsif request.declined? %>
              <span class="red-text font-weight-bold mt-3" style="color:Tomato;"><%= request.status %></span>
            <% end %>
          </div>
        </div>
        </div>

      <!-- Profile Modal, do not change! -->
      <div class="modal fade modal-profile" id="exampleModalCenter-<%= request.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content" style="height:500px;border-radius: 6px">
            <div>
              <h5 class="modal-title" id="exampleModalLongTitle"> </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" style="margin:20px" >

              <div style="text-align:center;">
                <%= cl_image_tag request.user.photo.key, crop: :fill, class: "avatar-large" %>
              </div><br>
              <h4 style="text-align:center;"> <%= request.user.first_name %> <%= request.user.last_name %> </h4>
              <hr style="margin-top:5px;background-color:#FF7662;height:2px;width:60%;text-align:left;margin-left:" >
              <span class="font-weight-light">
                Languages: <%= request.user.languages.map(&:name).join(', ') %><br>
                Age: <%= request.user.age %><br><br>
              </span>
              <span class="font-weight-normal"> <%= request.user.bio %> <span>
            </div>
          </div>
        </div>
      </div>
      <!-- Profile Modal, do not change! -->

        <% end  %>

<% else %>
        <h2> You don't have any requests to join your event yet. Check this page again in a few days! </h2>
<% end %>


    </div>
  </div>

app/views/requests/new.html.erb
<%= link_to root_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div class="container">
  <div class="card motivation-card" style="width: 100%;">
    <div class="card-body">
      <h5 class="card-title title"><strong>Send a message</strong></h5>

      <form action="<%= event_requests_path(@event) %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >

        <h5 class="card-input"></h5>
        <textarea id="motivation" name="request[motivation]" maxlength="200" placeholder="Let them know why you are interested in the event!" ></textarea><br>
        <p class="max-length" style="font-size: 12px; color: grey;">max 200 characters</p><br>
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    </div>
  </div>
</div>

app/views/requests/show.html.erb
<%= link_to root_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div class="container">

<h1> <%= @request.event.name %></h1>

<div class="card shadow p-3 mb-5 bg-white rounded" id="request-display" style="width: 30rem;">
  <%= cl_image_tag url_for(@request.event.photo), class:"card-img-top" %>
  <div class="card-img-overlay">
    <span class="badge badge-primary">
      <% @request.event.categories.each do |category| %>
        <% if category.present? %>
          <span class="badge badge-primary"> <%= category.name %> </span>
        <% end %>
      <% end %>
  </div>
  <div class="card-body">
    <div class="card-body">
      <h5 class="card-title">Event details</h5>
        <i class="far fa-calendar-alt"></i> <span style="color: gray"> <%= @request.event.date_time  %> </p></span>
        <i class="fas fa-map-marker-alt"></i> <span style="color: gray"> <%= @request.event.address %></span>
          <% if @request.event.ticket_url.present? %>
            <li><i class="far fa-calendar-alt"></i> Ticket URL: <span style="color: gray"> <%= @request.event.ticket_url  %> </span></li>
          <% end %>
        </ul>
      </div>
  </div>
  <div class="buddies-avatar">
    <%= cl_image_tag url_for(@request.user.photo), class:"avatar-large" %>
    <%= cl_image_tag url_for(@request.event.user.photo), class:"avatar-large" %>
  </div>

<button type="button" class="btn btn-primary">Message Buddy</button>
</div>

app/views/requests/submitted.html.erb
<%= link_to root_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div class="container">

<h2 class="p-2 my-1" style="text-align: center;color:#222"><strong>Buddy request has been submitted to <%= @request.event.user.first_name %> <%= @request.event.user.last_name %>!</strong> </h2>
<div class="card shadow p-3 mb-3 bg-white rounded" id="submitted-@requests" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= cl_image_tag @request.event.photo.key, class:"card-image",style:"border-radius:6px" %>

    </div>
    <div class="col-md-8 pl-2 pt-1">
        <h3 class="card-title mt-3"> <strong><%= @request.event.name  %> </strong></h3>
        <div class="card-details">
          <p><i class="fas fa-map-marker-alt"></i> <%= @request.event.address  %> </p>
          <p style="margin-bottom: 6px;"><i class="fas fa-calendar"></i> <%= @request.event.date_time.strftime("%m/%d/%Y") %> - <%= @request.event.date_time.strftime("%I:%M%p") %></p>

        </div>
    </div>
  </div>
</div>

  <p class="pl-2 mt-3 mb-0 pb-0" style="text-align: center;color:gray;"> Stay tuned!<br> You will get a message if<br> <%= @request.event.user.first_name %> accepts your request. </p>