config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/events/pending', to: 'events#my_events', as: 'my_events'
  get '/events/:id/delete', to: 'events#delete', as: 'delete_event'

  resources :events, except: [:edit] do
    resources :requests, only: [:new, :create]
    resources :users, only: [] do
      resources :messages, only: [:create]
    end
  end
  get '/requests/submitted/:id', to: 'requests#submitted', as: 'submitted_request'
  get '/events/:event_id/requests/incoming', to: 'requests#incoming', as: 'incoming_requests'
  resources :requests, only: [:show, :update]

  get '/inbox', to: 'messages#index', as: 'messages'
  get '/inbox/:user_id', to: 'messages#new', as: 'new_message'

  get '/welcome', to: 'pages#welcome', as: 'welcome'
  get '/calendar', to: 'pages#calendar', as: 'calendar'
  patch '/', to: 'pages#update_location'

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_calendar.html.erb
<%= month_calendar events: @events do |date, events| %>
  <%= link_to events_path({date: date}) do %>
    <div class="calendar-date">
      <%= date.day %>

      <div class="d-flex justify-content-start">
        <% events[0...3].each do |event| %>
          <% unless event.categories.empty? %>
            <i class="fas fa-circle" style="font-size: 7px; padding-right: 2px; color: <%= event.categories.first.color %>;"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/pages/_event_card.html.erb
        <div class="card-product">
          <%#= link_to event_path(event), style: "width: 45%;" do %>
          <%= link_to '', event_path(event), style:"width: 45%; background-size: cover; background-position: center; background-image: url('#{cl_image_path url_for(event.photo), height: 300, width: 400, crop: :fill}')"%>
          <%# end %>

  <div class="flex-column card-right">
    <ul class="card-product-infos ml-2">
      <%= link_to event_path(event) do %>
        <li><h2 style="margin: 0"><%= event.name %></h2></li>
      <% end %>
      <li style="font-size: 12px; margin: 0; margin-bottom:8px"><i class="fas fa-calendar"></i>  <%= event.date_time.strftime("%m/%d/%Y") %> - <%= event.date_time.strftime("%I:%M%p") %></li>
      <li class="event-card-address" style="font-size: 12px;"><i class="fas fa-map-marker-alt"></i> <%= event.address %></li>
    </ul>

            <div class="d-flex pb-1">
              <% unless event.categories.first.nil? %>
                <span class="card-filter ml-3" style="background-color: <%= event.categories.first.color %>"><%= event.categories.first.name %></span>
              <% end %>
              <% unless event.categories.second.nil? %>
                <span class="card-filter" style="background-color: <%= event.categories.second.color %>"><%= event.categories.second.name %></span>
              <% end %>
            </div>
                <div>
                  <%= cl_image_tag(event.user.photo.key, class: "card-avatar") %>
                </div>
          </div>
        </div>

app/views/pages/_filters.html.erb
<% if params[:categories].present? %>
  <div class="d-flex">

    <% if params[:categories].present? && params[:categories].include?("outdoors") %>
      <%= link_to 'outdoors', remove_from_category_params("outdoors"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "outdoors").color}" %>
    <% else %>
      <%= link_to 'outdoors', append_to_category_params("outdoors"), class:"calendar-filter deselected-filter", style:"background-color: #{Category.find_by(name: "outdoors").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("live music") %>
      <%= link_to 'live music', remove_from_category_params("live music"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "live music").color}" %>
    <% else %>
      <%= link_to 'live music', append_to_category_params("live music"), class:"calendar-filter deselected-filter", style:"background-color: #{Category.find_by(name: "live music").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("food") %>
      <%= link_to 'food', remove_from_category_params("food"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "food").color}" %>
    <% else %>
      <%= link_to 'food', append_to_category_params("food"), class:"calendar-filter deselected-filter", style:"background-color: #{Category.find_by(name: "food").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("drinks") %>
      <%= link_to 'drinks', remove_from_category_params("drinks"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "drinks").color}" %>
    <% else %>
      <%= link_to 'drinks', append_to_category_params("drinks"), class:"calendar-filter deselected-filter", style:"background-color: #{Category.find_by(name: "drinks").color}" %>
    <% end %>

  </div>

  <div class="d-flex">

    <% if params[:categories].present? && params[:categories].include?("sports") %>
      <%= link_to 'sports', remove_from_category_params("sports"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "sports").color}" %>
    <% else %>
      <%= link_to 'sports', append_to_category_params("sports"), class:"calendar-filter deselected-filter", style:"background-color: #{Category.find_by(name: "sports").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("theater") %>
      <%= link_to 'theater', remove_from_category_params("theater"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "theater").color}" %>
    <% else %>
      <%= link_to 'theater', append_to_category_params("theater"), class:"calendar-filter deselected-filter", style:"background-color: #{Category.find_by(name: "theater").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("festival") %>
      <%= link_to 'festival', remove_from_category_params("festival"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "festival").color}" %>
    <% else %>
      <%= link_to 'festival', append_to_category_params("festival"), class:"calendar-filter deselected-filter", style:"background-color: #{Category.find_by(name: "festival").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("other") %>
      <%= link_to 'other', remove_from_category_params("other"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "other").color}" %>
    <% else %>
      <%= link_to 'other', append_to_category_params("other"), class:"calendar-filter deselected-filter", style:"background-color: #{Category.find_by(name: "other").color}" %>
    <% end %>
  </div>
<% else %>
  <div class="d-flex">

    <% if params[:categories].present? && params[:categories].include?("outdoors") %>
      <%= link_to 'outdoors', remove_from_category_params("outdoors"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "outdoors").color}" %>
    <% else %>
      <%= link_to 'outdoors', append_to_category_params("outdoors"), class:"calendar-filter", style:"background-color: #{Category.find_by(name: "outdoors").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("live music") %>
      <%= link_to 'live music', remove_from_category_params("live music"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "live music").color}" %>
    <% else %>
      <%= link_to 'live music', append_to_category_params("live music"), class:"calendar-filter", style:"background-color: #{Category.find_by(name: "live music").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("food") %>
      <%= link_to 'food', remove_from_category_params("food"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "food").color}" %>
    <% else %>
      <%= link_to 'food', append_to_category_params("food"), class:"calendar-filter", style:"background-color: #{Category.find_by(name: "food").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("drinks") %>
      <%= link_to 'drinks', remove_from_category_params("drinks"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "drinks").color}" %>
    <% else %>
      <%= link_to 'drinks', append_to_category_params("drinks"), class:"calendar-filter", style:"background-color: #{Category.find_by(name: "drinks").color}" %>
    <% end %>

  </div>

  <div class="d-flex">

    <% if params[:categories].present? && params[:categories].include?("sports") %>
      <%= link_to 'sports', remove_from_category_params("sports"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "sports").color}" %>
    <% else %>
      <%= link_to 'sports', append_to_category_params("sports"), class:"calendar-filter", style:"background-color: #{Category.find_by(name: "sports").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("theater") %>
      <%= link_to 'theater', remove_from_category_params("theater"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "theater").color}" %>
    <% else %>
      <%= link_to 'theater', append_to_category_params("theater"), class:"calendar-filter", style:"background-color: #{Category.find_by(name: "theater").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("festival") %>
      <%= link_to 'festival', remove_from_category_params("festival"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "festival").color}" %>
    <% else %>
      <%= link_to 'festival', append_to_category_params("festival"), class:"calendar-filter", style:"background-color: #{Category.find_by(name: "festival").color}" %>
    <% end %>

    <% if params[:categories].present? && params[:categories].include?("other") %>
      <%= link_to 'other', remove_from_category_params("other"), class:"calendar-filter selected-calendar-filter", style:"background-color: #{Category.find_by(name: "other").color}" %>
    <% else %>
      <%= link_to 'other', append_to_category_params("other"), class:"calendar-filter", style:"background-color: #{Category.find_by(name: "other").color}" %>
    <% end %>
  </div>
<% end %>

app/views/pages/calendar.html.erb
<%= link_to root_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div class="container">

<div style="width: 90vw d-flex">
<h1 class="title py-3" style="width: 300px; font-size: 26px; margin-right: 30px" id="filters"><strong>Your upcoming events</strong></h1>
</div>

  <% if @events.length == 0 && params[:categories].nil?%>
    <p>You don't have any planned events!</p>
    <%= link_to "Search for a buddy", welcome_path, class: "btn btn-primary" %>
  <% else %>
      <%= render partial: "filters" %>
    <div class="pt-1 pb-3"></div>
    <%= render partial: "calendar", locals: { events: @events } %>

    <div class="d-flex flex-column-reverse pt-3" style="width: 360px">
      <% @events.each do |event|  %>
        <div class="card-product">

          <% if event.user == current_user%>
            <%= link_to '', new_message_path(event.requests.find_by(status:"Accepted").user, event: event) + "#event-chat", style:"width: 45%; background-size: cover; background-position: center; background-image: url('#{cl_image_path url_for(event.photo), height: 300, width: 400, crop: :fill}')"%>
          <% else %>
            <%= link_to '', new_message_path(event.user, event: event) + "#event-chat", style:"width: 45%; background-size: cover; background-position: center; background-image: url('#{cl_image_path url_for(event.photo), height: 300, width: 400, crop: :fill}')"%>
          <% end %>

          <div class="flex-column card-right">
            <ul class="card-product-infos ml-2">

          <% if event.user == current_user%>
              <%= link_to new_message_path(event.requests.find_by(status:"Accepted").user, event: event) + "#event-chat" do %>
                <li><h2 style="margin: 0"><%= event.name %></h2></li>
              <% end %>
          <% else %>
              <%= link_to new_message_path(event.user, event: event) + "#event-chat" do %>
                <li><h2 style="margin: 0"><%= event.name %></h2></li>
              <% end %>
          <% end %>

      <li class="event-card-address"><i class="fas fa-map-marker-alt"></i> <%= event.address %></li>
      <li style="font-size: 12px; margin: 0; margin-bottom:8px"><i class="fas fa-calendar"></i> <%= event.date_time.strftime("%m/%d/%Y") %> - <%= event.date_time.strftime("%I:%M%p") %></li>
            </ul>

            <div class="d-flex pb-1">
              <% unless event.categories.first.nil? %>
                <span class="card-filter ml-3" style="background-color: <%= event.categories.first.color %>"><%= event.categories.first.name %></span>
              <% end %>
              <% unless event.categories.second.nil? %>
                <span class="card-filter" style="background-color: <%= event.categories.second.color %>"><%= event.categories.second.name %></span>
              <% end %>
            </div>
            <% if event.user == current_user%>
              <%= link_to new_message_path(event.requests.find_by(status:"Accepted").user, event: event) + "#event-chat" do %>
              <div style="position: absolute; top: 4px; left: 4px; background: white; width: 136px; height: 44px; border-radius: 300px; opacity: 0.7">
                <p style="position: absolute; right: 10px; font-size: 12px; color: #444; top: 12px;">Buddies!</p>
              </div>
              <div>
                <%= cl_image_tag(event.requests.find_by(status:"Accepted").user.photo.key, class: "card-avatar", style: "top: 6px; left: 6px; border: 1px solid rgba(255,255,255,0.8)") %>
                <%= cl_image_tag(event.user.photo.key, class: "card-avatar", style: "top: 6px; left: 35px; border: 1px solid rgba(200,200,200,0.7)") %>
              </div>
              <% end %>
            <% else %>
              <%= link_to new_message_path(event.user, event: event) + "#event-chat" do %>
              <div style="position: absolute; top: 4px; left: 4px; background: white; width: 136px; height: 44px; border-radius: 300px; opacity: 0.7">
                <p style="position: absolute; right: 10px; font-size: 12px; color: #444; top: 12px;">Buddies!</p>
              </div>
              <div>
                <%= cl_image_tag(event.requests.find_by(status:"Accepted").user.photo.key, class: "card-avatar", style: "top: 6px; left: 6px; border: 1px solid rgba(255,255,255,0.8)") %>
                <%= cl_image_tag(event.user.photo.key, class: "card-avatar", style: "top: 6px; left: 35px; border: 1px solid rgba(200,200,200,0.7)") %>
              </div>
              <% end %>
            <% end %>
          </div>
        </div>

      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<%= link_to welcome_path, class: "back-button" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
<div class="container">

  <% if @events.length == 0 %>
    <div class="py-3"><p></p></div>
    <h3 class="mt-4 mb-5">No events listed at the location "<%= current_user.search_location %>"... :(</h3>
    <h2 class="mb-3 mt-2">Try again</h2>
          <%= form_for @user, url: root_path, method: :patch do |f| %>
        <div class="d-flex">
          <div>
          <%= f.text_field :search_location, placeholder: 'Input a location', value: "", label:false %>
          </div>
          <div>
          <%= f.button'<i class="fa fa-lock" aria-hidden="true"></i> Register'.html_safe, class: "btn btn-primary", style: "padding: 7px 12px; margin-bottom: 2px; border-radius: 2px; color: white;" do %>
            <i class="fas fa-location-arrow"></i>
          <% end %>
          </div>
          <% end %>
        </div>
    <h2 class="mt-5">or</h2>
    <%= link_to "Suggest an event", new_event_path, class: "btn-lg btn-primary mt-2 mb-5" %>
  <% else %>
    <div class="w-100">
      <h1 class="title py-3" id="filters">Browse events</h1>
    </div>
    <%= render partial: "filters" %>

    <div class="calendar-location mt-3" id="calendar-top">
      <%= current_user.search_location %>
    </div>
    <%= render partial: "calendar", locals: { events: @events } %>
    <div class="my-2"></div>

    <%= form_tag "#calendar-top", method: :get, class: "d-flex" do %>
       <%= text_field_tag :query,
                      params[:query],
                      class: "form-control",
                      placeholder: "Search by keyword" %>
                    <%= button_tag type: 'submit', class: "btn btn-primary mb-3" do %>
                      <i class='fas fa-search'></i>
                    <% end %>
                  <% end %>

    <% if @events.length > 0 %>
      <% if @search_results.length == 0 && params[:query] != "" && params[:query] != nil%>
        <p>No results for "<%= params[:query] %>"</p>
      <% end %>
      <% if @search_results.length > 0 && params[:query] != "" && params[:query] != nil%>

    <div class="w-100">
      <h1 class="title py-3">Search Results</h1>
    </div>

        <div class="d-flex flex-column-reverse" style="width: 360px">
          <% @search_results.each do |event|  %>
            <%= render partial: "event_card", locals: { event: event } %>
          <% end %>
        </div>
      <% end %>


    <div class="w-100">
      <h1 class="title pb-3 pt-4">Suggested for you</h1>
    </div>

      <div class="d-flex flex-column-reverse" style="width: 360px">
        <% @events.each do |event|  %>
          <%= render partial: "event_card", locals: { event: event } %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/welcome.html.erb
<span class="back-button"></span>
<%= link_to image_tag("logo.png", width: 20, class: 'page-title', style:"width: 112px") %>
  <div class="container">

    <div class="py-2"></div>
      <%= cl_image_tag @user.photo.key, crop: :fill, class: "avatar-welcome-page mt-3 mb-2" %>
      <h1 class="mt-2 mb-5"><strong>Hi <%= @user.first_name %></strong></h1>
      <h2 class="mb-3 mt-2">Browse events</h2>

      <%= form_for @user, url: root_path, method: :patch do |f| %>
        <div class="d-flex">
          <div>
          <%= f.text_field :search_location, placeholder: 'Input a location', value: "", label:false %>
          </div>
          <div>
          <%= f.button class: "btn btn-primary", style: "padding: 7px 12px; margin-bottom: 2px; border-radius: 2px; color: white;" do %>
            <i class="fas fa-location-arrow"></i>
          <% end %>
          </div>
          <% end %>
        </div>
      <h2 class="mt-4">or</h2>
      <%= link_to "Suggest an event", new_event_path, class: "btn-lg btn-primary mt-2", style: "color: white;" %>

  </div>
  </div>

<style>
  @media screen and (max-width: 600px) {
  .container {
    display: flex;
    justify-content: center;
    flex-direction: column;
    height: 100vh;
    padding-top: 26px;
  }
}

</style>